api_platform:
    show_webby: false # supprime l'araignée webby
    mapping: # permet de configurer les chemins d'accès aux ressources si aucune annotation n'est présente
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        # permet d'avoir un champ api_key dans le header de la requête et dans Authorize de Swagger
        # api_keys:
        #      apiKey:
        #         name: Authorization
        #         type: header