vich_uploader:
    db_driver: orm

    mappings:
       company_logo:
           uri_prefix: /images/logos
           upload_destination: '%kernel.project_dir%/public/images/logos'
           namer: Vich\UploaderBundle\Naming\OrignameNamer
    
    metadata:
        type: attribute
