controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login:
    path: /api/login

authentication_token:
    path: /api/authentication_token
    methods: ['POST']

api_refresh_token:
    path: /api/token/refresh