# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
        
        

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\OpenApi\OpenApiFactory: #déclare le service OpenApiFactory
        decorates: 'api_platform.openapi.factory' #déclare le service OpenApiFactory comme décorateur de api_platform.openapi.factory
        arguments: ['@App\OpenApi\OpenApiFactory.inner'] #indique où chercher le service OpenApiFactory
        autoconfigure: false #désactive l'autoconfiguration

    App\Repository\DependencyRepository: #injection de dépendance du chemin racine du projet 
        arguments: ['%kernel.project_dir%']

    # App\Serializer\CompanyContextBuilder: #déclaration du service CompanyContextBuilder
    #     decorates: 'api_platform.serializer.context_builder' 
    #     autoconfigure: false
